stages:
    - build

Build NodeJS App:
    stage: build
    script:
        - whoami
        - cd /var/www/html/server/
        - sudo chown -R $USER .git/
        - sudo git pull origin main
        - sudo pm2 restart "formestay"
    tags:
        - formestay